from __future__ import annotations

from typing import Protocol
from sorter.domain.models import MachinePose


class MotionPort(Protocol):
    def home_axes(self) -> None: ...
    def move_xy(self, x_mm: float, y_mm: float) -> None: ...
    def move_z(self, z_mm: float) -> None: ...
    def move_c(self, c_mm: float) -> None: ...
    def get_pose(self) -> MachinePose: ...
    def wait_until_idle(self) -> None: ...
