from __future__ import annotations

from typing import Protocol

from sorter.domain.events import DomainEvent
from sorter.domain.models import MachineSnapshot


class RunStorePort(Protocol):
    def start_run(self, run_id: str, mode: str, scenario_name: str | None, config_snapshot: dict) -> None: ...
    def append_event(self, run_id: str, seq: int, event: DomainEvent) -> None: ...
    def save_snapshot(self, run_id: str, seq: int, snapshot: MachineSnapshot) -> None: ...
    def save_frame(self, run_id: str, seq: int, frame_id: str, path: str | None, pile_key: str | None, recognized_name: str | None, confidence: float | None) -> None: ...
    def finish_run(self, run_id: str, status: str) -> None: ...
